### ISSUE TITLE
Upper / Lowercase file naming

### ISSUE THREAD

**Issue by sockeqwe** [lurbas/Search#1]
Hi,
I have cloned your sample project, and there is a very annoying problem with mac's file system that doesn't distinguish between letter case (upper and lower case)
- app/src/main/java/com/lucasurbas/search/db/DatabaseORMlite.java --> Note that ORM**l**ite.java and not ORM**L**ite.java. I guess you have renamed it afterwards to **L**ite.java but it has been commited as lower case into your repo while the java class name is in upper case.
- app/src/main/java/com/lucasurbas/search/db/ORMliteHelper.java  --> ORM**l**iteHelper.java --> same here

**Comment by lurbas** [comment]
Yes, that happend to me before, will fix asap

**Comment by lurbas** [comment]
Fixed
